version: "3.9"
services:
  wallet-project:
    container_name: wallet-project
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - wallet-project-db
      - wallet-project-redis
    volumes:
      - wallet-project-media:/media
      - wallet-project-static:/static
    command: python /app/code/manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - "8000:8000"

  wallet-project-db:
    container_name: wallet-project-db
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wallet-project-db-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"

  wallet-project-redis:
    container_name: wallet-project-redis
    image: redis:7
    ports:
      - "7739:6739"


  wallet-project-celery:
    container_name: wallet-project-celery
    build: .
    command: celery -A src worker --loglevel=INFO
    volumes:
      - ./code/src:/app/code/src
    depends_on:
      - wallet-project
    environment:
      PYTHONPATH: /app/code

  wallet-project-celery-beat:
    container_name: wallet-project-celery-beat
    build: .
    command: celery -A src beat -l INFO
    volumes:
      - ./code/src:/app/code/src
    depends_on:
      - wallet-project
    environment:
      PYTHONPATH: /app/code



volumes:
  wallet-project-db-data: { }
  wallet-project-media: { }
  wallet-project-static: { }
