# Generated by Django 4.1.7 on 2023-04-03 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'amount_currency')},
        ),
    ]
