# Generated by Django 4.1.7 on 2023-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallet_wallet_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
