# Generated by Django 4.1.7 on 2023-04-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Мой кошелёк', max_length=30, unique=True),
        ),
    ]
