# Generated by Django 4.1.7 on 2023-04-04 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0006_alter_wallet_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'amount_currency')},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Мой кошелёк', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'name'), ('user', 'amount_currency')},
        ),
    ]
