# Generated by Django 4.1.7 on 2023-04-04 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0007_alter_wallet_unique_together_alter_wallet_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'amount_currency')},
        ),
    ]
