# Generated by Django 4.1.7 on 2023-04-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_alter_wallet_unique_together'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_operations', to='wallets.wallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_operations', to='wallets.wallet'),
        ),
    ]
