# Generated by Django 4.1.7 on 2023-04-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_wallettransaction_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='operation_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('WITHDRAW', 'Withdraw')], max_length=8),
        ),
    ]
